# 配置文件

# 应用名称
[application]
    name         = "博客"
    url          = "http://localhost"
    host         = ""
    port         = 18091
    debug        = true
    markdowndir = "blogs"
    icp          = "备案号"
    statistics   = ""
    secret       = ""                 # github 钩子中配置的 Secret， 要和钩子的配置保持一致

# 日志相关的配置
[log]
    # 日志保存位置，默认是应用根目录下生成日志文件
    # 如果以 / 开始，就是使用绝对路径，如： /logs
    # 如果不是以 / 开始的目录，如 logs ， 会自动放在应用根目录下创建 $appPath/logs
    dir = "logs"
    # 日志格式， 适配的 time.Format 的格式
    # 如果为空就会定义一个默认的格式 "2006-01/02"
    format = ""
    # 日志模式，共有三种
    # close 关闭, 如果关闭将不会再写日志
    # file 写入文件，会写入到上面的 log_dir 配置的目录中
    # stdout 写入到标准输入，一般就是终端直接打印日志，建议 debug 的时候配置
    mode = "file"
    # 是否记录访问日志，就是浏览器访问系统时产生的日志，
    # 只有上面的 mode 不为 close， 并且 access 为 true 的时候才会记录日志
    access = true

[path]
    rootPath="D:/newfiles/softwares/go_workspace/src/beegolearn"
